baseURL: https://alexnorell.com/
languageCode: en-us
title: Alex Norell
theme: hugo-theme-m10c
enableGitInfo: True
paginate: 5

frontmatter:
  date:
    - "date"
    - ":git"
    - ":fileModTime"
    - "publishDate"
  lastmod:
    - "date"
    - "lastmod"
    - ":git"
    - ":fileModTime"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: -110
  - identifier: categories
    name: Categories
    url: /categories/
    weight: -100
  - identifier: tags
    name: Tags
    url: /tags/
    weight: -90

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 4

params:
  author: "Alex Norell"
  description: "Software Engineer with a passion for IoT"
  date_format: "January 2, 2006"
  avatar: "images/avatar.jpg"
  favicon: "images/favicon/favicon.ico"
  utterences:
    repo: alexnorell/website
    issue-term: pathname
    theme: dark-blue

  social:
    - name: github
      url: "https://github.com/alexnorell"
    - name: linkedin
      url : "https://linkedin.com/in/alexnorell"
    - name: twitter
      url: "https://twitter.com/alexnorell"
    - name: youtube
      url: "https://youtube.com/alexnorell"

  style:
    darkestColor: '#282a36'
    darkColor: '#21222B'
    primaryColor: '#bd93f9'
    lightColor: '#f8f8f2'
    lightestColor: '#50fa7b'
