baseURL: https://alexnorell.com/
languageCode: en-us
title: Alex Norell
theme: strata
enableGitInfo: True

frontmatter:
  date:
    - "date"
    - ":git"
    - ":fileModTime"
    - "publishDate"
  lastmod:
    - "date"
    - "lastmod"
    - ":git"
    - ":fileModTime"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4

params:
  author: "Alex Norell"
  description: "Software Engineer"
  date_format: "January 2, 2006"
  bio: "Software Engineer @ [Sleep Number Labs](https://sleepnumberlabs.com)"
  avatar: 
    local: "avatar.jpg"
  bg_credit: "Photo by Gauravdeep Singh Bansal on Unsplash"
  
  social:
    - github: "alexnorell"
    - linkedin: "alexnorell"
    - twitter: "alexnorell"
    - youtube: "alexnorell"
    - strava: "alexnorell"

  about:
    title: Hi. I'm Alex.
    content: |
      I am a Computer Engineer with a strong passion for everthing IoT. Hardware, Firmware, Software, Cloud, Security, Product.

  recentposts:
    title: Recent posts

  copyright: 
    - "Design: [HTML5 UP](https://html5up.net)"
