baseURL: "http://alexnorell.com/"
languageCode: "en-us"
title: "Alex Norell"
theme: "strata"

enableGitInfo: true

# frontmatter:
#   date: ["date", "publishDate", "lastmod"]
#   lastmod: [":git", "lastmod", "date", "publishDate"]
#   publishDate: ["publishDate", "date"]
#   expiryDate: ["expiryDate"]

params:
  author: "Alex Norell"
  title: "Title"
  description: "Computer Engineer"
  date_format: "January 2, 2006"
  bio: "Computer Engineer @ [SleepIQ Labs](https://sleepiqlabs.com)"
  
  social:
    - github: "alexnorell"
    - linkedin: "alexnorell"
    - twitter: "alexnorell"
    - keybase: "alexnorell"
    - youtube: "alexnorell"
    
  
  about:
    hide: false
    title: "This is my site"
    content: "This is content in the about section"
  
  portfolio:
    hide: false
    title: "Recent Work"
    gallery:
      - image: 'fulls/01.jpg'
        thumb: 'thumbs/01.jpg'
        title: 'This is a gallery post'
        description: 'This goes into the gallery post'

  recentposts:
    hide: false
    title: "Recent blog posts"

  contact:
    hide: true

  copyright: 
    - "Design: [HTML5 UP](https://html5up.net)"
