baseURL: "http://alexnorell.com/"
languageCode: "en-us"
title: "Alex Norell"
theme: "strata"

enableGitInfo: true

frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: [":git", "lastmod", "date", "publishDate"]
  publishDate: ["publishDate", "date"]
  expiryDate: ["expiryDate"]

params:
  author: "Alex Norell"
  title: "Title"
  description: "Computer Engineer"
  date_format: "January 2, 2006"

  sidebar:
    bio: "Computer Engineer @ [SleepIQ Labs](https://sleepiqlabs.com)"

    github: "alexnorell"
    gitlab: "alexnorell"
    linkedin: "alexnorell"
    twitter: "alexnorell"
    stackoverflow: "alexnorell"
    keybase: "alexnorell"
    youtube: "alexnorell"
    gravatar: "alex.norell@gmail.com"
    copyright: ["Design: [HTML5 UP](//html5up.net)"]

  about:
    hide: false
    title: "This is my site"
    content: "This is content in the about section"
  
  portfolio:
    hide: false
    title: "Recent Work"
    gallery:
      - image: 'fulls/01.jpg'
        thumb: 'thumbs/01.jpg'
        title: 'This is a gallery post'
        description: 'This goes into the gallery post'

  recentposts:
    hide: false
    title: "Recent blog posts"
    email: "nope@gmail.com"

  contact:
    hide: true
