baseURL: https://alexnorell.com/
languageCode: en-us
title: Alex Norell
theme: hugo-theme-m10c
enableGitInfo: True
paginate: 10

frontmatter:
  date:
    - "date"
    - ":git"
    - ":fileModTime"
    - "publishDate"
  lastmod:
    - "date"
    - "lastmod"
    - ":git"
    - ":fileModTime"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"

menu:
  main:
    - identifier: home
      name: Home
      url: /
    - identifier: tags
      name: Tags
      url: /tags/

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 4

params:
  author: "Alex Norell"
  description: "Software Engineer"
  date_format: "January 2, 2006"
  bio: "Software Engineer @ [Sleep Number Labs](https://sleepnumberlabs.com)"
  avatar: "images/avatar.jpg"

  social:
    - name: github
      url: "https://github.com/alexnorell"
    - name: linkedin
      url : "https://linkedin.com/alexnorell"
    - name: twitter
      url: "https://twitter.com/alexnorell"
    - name: youtube
      url: "https://youtube.com/alexnorell"

  about:
    title: Hi. I'm Alex.
    content: |
      I am a Computer Engineer with a strong passion for everthing IoT. Hardware, Firmware, Software, Cloud, Security, Product.

  recentposts:
    title: Recent posts

  style:
    darkestColor: '#282a36'
    darkColor: '#21222B'
    primaryColor: '#bd93f9'
    lightColor: '#f8f8f2'
    lightestColor: '#50fa7b'

  copyright:
    - "Design: [HTML5 UP](https://html5up.net)"
