baseURL: "https://alexnorell.com/"
languageCode: "en-us"
title: "Alex Norell"
theme: "strata"
enableGitInfo: True

frontmatter:
  date:
    - "date"
    - ":git"
    - ":fileModTime"
    - "publishDate"
  lastmod:
    - ":git"
    - ":fileModTime"
    - "lastmod"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"

params:
  author: "Alex Norell"
  description: "Software Engineer"
  date_format: "January 2, 2006"
  bio: "Software Engineer @ [Sleep Number Labs](https://sleepnumberlabs.com)"
  avatar: 
    local: "avatar.jpg"
  bg_credit: "Photo by Gauravdeep Singh Bansal on Unsplash"
  
  social:
    - github: "alexnorell"
    - linkedin: "alexnorell"
    - twitter: "alexnorell"
    - keybase: "alexnorell"
    - youtube: "alexnorell"

  about:
    title: "Some of the stuff I want to share"
    content: "This is more of a technical challenge rather than an actual blog. It is place for me to try out different server technologies, as well as write down how I did it."

  recentposts:
    title: "Recent blog posts"

  copyright: 
    - "Design: [HTML5 UP](https://html5up.net)"
